### PR TITLE
ARGO - event driven

### PR DESCRIPTION
**Pull request by lbesnard**

### CODE REVIEW

**Comment by jonescc** [comment]
The custom queries used by iNewOrModifiedFileList in HarvestArgoPlatforms and HarvestArgoProfiles need to be modified to match manifest file indexing changes (or replaced)

**Comment by jonescc** [comment]
Or perhaps you did this already?

**Comment by lbesnard** [comment]
well I'll check, but I just did a copy and paste of those custom querys. I didn't replace any columns and tables as I assumed they should be similar

**Comment by danfruehauf** [comment]
Just got that:
```
INFO 10/20/15 1:50 PM:liquibase: Successfully released change log lock
Exception in thread "main" java.lang.Error: java.lang.Error: java.lang.Error: java.lang.Error: java.lang.Error: Unresolved compilation problems: 
        Syntax error, insert ";" to complete Statement
        The method intValue() is undefined for the type HarvestArgoProfilePositions

        at argo.argo_harvester_0_1.Argo_harvester.iUpdateIndex_1Process(Argo_harvester.java:1340)
        at argo.argo_harvester_0_1.Argo_harvester.runJobInTOS(Argo_harvester.java:3975)
        at argo.argo_harvester_0_1.Argo_harvester.main(Argo_harvester.java:3723)
Caused by: java.lang.Error: java.lang.Error: java.lang.Error: java.lang.Error: Unresolved compilation problems: 
        Syntax error, insert ";" to complete Statement
        The method intValue() is undefined for the type HarvestArgoProfilePositions

        at argo.argo_harvester_0_1.Argo_harvester.tRunJob_4Process(Argo_harvester.java:1517)
        at argo.argo_harvester_0_1.Argo_harvester.iUpdateIndex_1Process(Argo_harvester.java:1332)
        ... 2 more
Caused by: java.lang.Error: java.lang.Error: java.lang.Error: Unresolved compilation problems: 
        Syntax error, insert ";" to complete Statement
        The method intValue() is undefined for the type HarvestArgoProfilePositions

        at argo.argo_harvester_0_1.Argo_harvester.tRunJob_1Process(Argo_harvester.java:1701)
        at argo.argo_harvester_0_1.Argo_harvester.tRunJob_4Process(Argo_harvester.java:1503)
        ... 3 more
Caused by: java.lang.Error: java.lang.Error: Unresolved compilation problems: 
        Syntax error, insert ";" to complete Statement
        The method intValue() is undefined for the type HarvestArgoProfilePositions

        at argo.harvestargoprofilepositions_0_1.HarvestArgoProfilePositions.iDeletedFileList_1Process(HarvestArgoProfilePositions.java:693)
        at argo.harvestargoprofilepositions_0_1.HarvestArgoProfilePositions.runJobInTOS(HarvestArgoProfilePositions.java:1223)
        at argo.harvestargoprofilepositions_0_1.HarvestArgoProfilePositions.runJob(HarvestArgoProfilePositions.java:1076)
        at argo.argo_harvester_0_1.Argo_harvester.tRunJob_1Process(Argo_harvester.java:1645)
        ... 4 more
Caused by: java.lang.Error: Unresolved compilation problems: 
        Syntax error, insert ";" to complete Statement
        The method intValue() is undefined for the type HarvestArgoProfilePositions

        at argo.harvestargoprofilepositions_0_1.HarvestArgoProfilePositions.iNewOrModifiedFileList_1Process(HarvestArgoProfilePositions.java:890)
        at argo.harvestargoprofilepositions_0_1.HarvestArgoProfilePositions.iDeletedFileList_1Process(HarvestArgoProfilePositions.java:685)
        ... 7 more
2015-10-20 13:43:32;O97VnJ;O97VnJ;O97VnJ;11349;ARGO;Argo_harvester;_yAc4sDzlEeKIJ9HE2ojUMg;0.1;Default;;begin;;
```

**Comment by jonescc** [comment]
Probably don't need 

" where (file_harvest.last_moddate_harvested <> indexed_file.modified " +
"    or  file_harvest.last_moddate_harvested is null) "

You should harvest it if the pipeline tells you to

**Comment by lbesnard** [comment]
> intValue() is u

arg, saw some typos

**Comment by jonescc** [comment]
Custom Query for HarvestArgoPlatforms should be something like:

		"select indexed_file.id, indexed_file.url, indexed_file.modified " +
		"  from indexed_file " +
		"  join index_job " +
		"    on indexed_file.job_id = index_job.id " +
		"   and indexed_file.last_indexed_run = index_job.last_run_no " +
		"   and index_job.name = ? " +
		"  left join file_harvest " +
		"    on file_harvest.file_id = indexed_file.id " +
		"   and file_harvest.harvest_type = ? " +
 		"   and file_harvest.last_change_type <> 'deleted' " +
                "  join australian_floats " +
                "    on indexed_file.url like '%/'||trim(australian_floats.platform_number)||'/%_meta.nc' " +
		" where not indexed_file.deleted "

**Comment by jonescc** [comment]
Custom query for HarvestArgoProfiles should be something like:

    "select indexed_file.id, indexed_file.url, indexed_file.modified " +
    "  from indexed_file " +
    "  join index_job " +
    "    on indexed_file.job_id = index_job.id " +
    "   and indexed_file.last_indexed_run = index_job.last_run_no " +
    "   and index_job.name = ? " +
    "  left join file_harvest " +
    "    on file_harvest.file_id = indexed_file.id " +
    "   and file_harvest.harvest_type = ? " +
    "   and file_harvest.last_change_type <> 'deleted' " +
    "  join australian_floats " +
    "    on indexed_file.url like '%/'||trim(australian_floats.platform_number)||'/profiles/%.nc' " +
    " where not indexed_file.deleted "

**Comment by jonescc** [comment]
Or even better remove the use of custom queries

**Comment by lbesnard** [comment]
> Or even better remove the use of custom queries

unfortunately can't afford that

**Comment by jonescc** [comment]
No probs.  The logic for identifying new/modified files changed.

Also possibly affects SOOP_TMV, ANMN_NRS_NRT_WAVE_TIMESERIES, ANMN_NRS_RT_METO_TIMESERIES, ANMN_NRS_RT_BIOGEOCHEM_TIMESERIES and ANFOG_RT - which use indexed_files/file_harvest to identify changes

**Comment by danfruehauf** [comment]
@lbesnard :+1: Works!

**Pull request merged**
