### PR TITLE
 aodn_aims_ctd : add gist index to _map table

### PR DESCRIPTION
**Pull request by bpasquer**
this PR is related to https://github.com/aodn/content/issues/124 
the  index used in the ORDER BY query alreqady exist. 
A gist index on geometry is already present in the measurement table but was missing in the _map table.

### CODE REVIEW

**Comment by danfruehauf** [comment]
@bpasquer Is this GTG?

**Comment by danfruehauf** [comment]
Should we squash the commits? Or do you want them as is?

**Comment by danfruehauf** [comment]
@bpasquer squashed them for you.

**Comment by bpasquer** [comment]
Squash
On 12 Aug 2015, at 4:21 pm, Dan Fruehauf <notifications@github.com<mailto:notifications@github.com>> wrote:


Should we squash the commits? Or do you want them as is?

—
Reply to this email directly or view it on GitHub<https://github.com/aodn/harvesters/pull/265#issuecomment-130184321>.

Dr. Benedicte Pasquer - Project Officer
Monday - Friday 9am -3pm
IMOS e-Marine Information Infrastructure
University of Tasmania
Ph: +61 3 6226 1927













University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Pull request merged**
