### PR TITLE
SRS OC LJCO WWS - new harvester

### PR DESCRIPTION
**Pull request by lbesnard**
* create a new harvester with no pipeline (for review only)
 * next commit will be pipeline proof
 * no metadata record created yet, needs vocabulary
 * requires geoserver layers with multi WFS, single WMS
 * files and filenames need to me modified (removed gatt, see chat with
   GG)

### CODE REVIEW

**Comment by lbesnard** [comment]
FYI @smancini

**Comment by xhoenner** [comment]
I tested out the first commit: the harvester ran smoothly. A few minor comments below:

* In the `measurements_weather` and `measurements_water` tables, I'd suggest changing the field measurement to measurement_id.
* In the `srs_oc_ljco_wws_timeseries_water_data` view: "TIME" is not at timezone 'UTC'.

**Comment by lbesnard** [comment]
## DEPLOYMENT PLAN

## Chef
To merge
https://github.com/aodn/chef/pull/259

## Geonetwork
@atkinsn , 3 metadata records need to be created
* __WQM FV02 daily product__
srs_oc_ljco_wws_daily_wqm_fv02_timeseries_map
srs_oc_ljco_wws_daily_wqm_fv02_timeseries_data

* __WQM FV01 hourly data__
srs_oc_ljco_wws_hourly_wqm_fv01_timeseries_map
srs_oc_ljco_wws_hourlt_wqm_fv01_timeseries_data

* __WEATHER and WATER SAMPLING F01 monthly data__
srs_oc_ljco_wws_mtw_monthly_fv01_timeseries_map
srs_oc_ljco_wws_mtw_monthly_fv01_timeseries_water_data
srs_oc_ljco_wws_mtw_monthly_fv01_timeseries_weather_data


## geoserver
Layers need to be created, waiting for UUID

## data services
To merge
https://github.com/aodn/data-services/pull/361


## PS
75 GB of data in incoming. Waiting for Yi's reply. Also waiting for weather FV01 files to be reprocessed.
No CF check because of issue https://github.com/aodn/compliance-checker/issues/101

**Comment by danfruehauf** [comment]
@lbesnard Can this go in?

**Comment by lbesnard** [comment]
it can, as i said yesterday, the big files could be moved to a different dir

**Comment by atkinsn** [comment]
@lbesnard I had already created the record for the "weather and water sampling" last year for you - uuid = e219c92c-696c-407a-ac1b-f451b8d88f06
And I have created the following 2 new ones:
WQM daily = 1fd45581-f79b-48ac-8a93-3ef70d6832dc 
WQM hourly = 43c8e6e0-05b2-4b02-a5c4-089914af37f7

**Comment by lbesnard** [comment]
@atkinsn thanks, we only need to create the vocab now

**Pull request merged**
