### PR TITLE
Event driven AATAMS_SATTAG_DM

### PR DESCRIPTION
**Pull request by danfruehauf**

### CODE REVIEW

**Comment by xhoenner** [comment]
do you want me to merge that @danfruehauf ?

**Comment by danfruehauf** [comment]
I'd like to test it first :)

**Comment by danfruehauf** [comment]
Or... Have another person test and review it, I mean.

**Comment by xhoenner** [comment]
Does https://github.com/aodn/data-services/pull/242 need to be merged 1st?

**Comment by danfruehauf** [comment]
Yes, they all need to go in at the same time. I'd like to go over it with you when you have time, explain you the changes and why they are needed.

**Comment by danfruehauf** [comment]
@xhoenner In short, I tried with the new harvester changes (I rebased on top of them) and I get that when running the harvester:
```
INFO 12/8/15 5:06 PM:liquibase: Successfully acquired change log lock
INFO 12/8/15 5:06 PM:liquibase: Reading from aatams_sattag_dm.databasechangelog
INFO 12/8/15 5:06 PM:liquibase: Reading from aatams_sattag_dm.databasechangelog
INFO 12/8/15 5:06 PM:liquibase: Successfully released change log lock
Exception in component iIndexFiles_1_iFiles
java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iIndexFiles_1_iFilesProcess(aatams_sattag_dm_harvester.java:4132)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.tPostgresqlConnection_1Process(aatams_sattag_dm_harvester.java:1373)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.runJobInTOS(aatams_sattag_dm_harvester.java:6757)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.main(aatams_sattag_dm_harvester.java:6545)
2015-12-08 17:06:05;iQRoEk;iQRoEk;iQRoEk;31620;AATAMS_SATTAG_DM;aatams_sattag_dm_harvester;_MOp9oJgmEeOMouHqP27dXg;0.1;Default;;begin;;

2015-12-08 17:06:07;iQRoEk;iQRoEk;iQRoEk;31620;AATAMS_SATTAG_DM;aatams_sattag_dm_harvester;_MOp9oJgmEeOMouHqP27dXg;0.1;Default;;end;failure;1928
```

**Comment by xhoenner** [comment]
Well, it looks like there's an issue with the iIndexFiles_1_iFiles component, which I didn't implement in the PR that @lbesnard merged today.

**Comment by danfruehauf** [comment]
Alright, that's fine then, better sort that out then we continue with that. The rest of the pieces work OK :)

**Comment by xhoenner** [comment]
> better sort that out then

Not sure how though, I'll need your assistance for that.

**Comment by danfruehauf** [comment]
Me??? @jonescc Help!!!

**Comment by danfruehauf** [comment]
I gonna look into that now...

**Comment by jonescc** [comment]
Note that log above refers to iIndexFiles_1 which is used by the old harvesters not manifest harvesters

**Comment by danfruehauf** [comment]
@jonescc Yeah thanks. I realized I had some problems with the previous branch I pushed. I rebuilt the harvester and will try again. If it doesn't work I'll probably bother you...

**Comment by danfruehauf** [comment]
@jonescc Alright, same error again unfortunately:
```
Exception in component iIndexFiles_1_iFiles
java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iIndexFiles_1_iFilesProcess(aatams_sattag_dm_harvester.java:4350)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.tPostgresqlConnection_1Process(aatams_sattag_dm_harvester.java:1386)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.runJobInTOS(aatams_sattag_dm_harvester.java:6975)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.main(aatams_sattag_dm_harvester.java:6763)
2016-01-08 12:47:03;cl84r3;cl84r3;cl84r3;17314;AATAMS_SATTAG_DM;aatams_sattag_dm_harvester;_MOp9oJgmEeOMouHqP27dXg;0.1;Default;;begin;;

2016-01-08 12:47:05;cl84r3;cl84r3;cl84r3;17314;AATAMS_SATTAG_DM;aatams_sattag_dm_harvester;_MOp9oJgmEeOMouHqP27dXg;0.1;Default;;end;failure;2006
```

Need your help :)

**Comment by danfruehauf** [comment]
@jonescc Scratch that, I've built `master` by accident.

**Comment by danfruehauf** [comment]
I think I understand the problem now better regarding that harvester. I'll try to explain. @xhoenner please correct me if I'm wrong.

This harvester harvests CTD and dive data from mdb files. CTD is harvested from **ALL** files - that's the first index component. Dive data is harvested from all files except for a select few - that's the second index component. When migrating this harvester to be event driven, things don't work because iIndexFiles used to have an `exclude` option which doesn't exist for `iFileList` - that is when harvesting dive data.

Possible solutions are below.

### 2 Harvesters

Have 2 harvesters, one for CTD and one for dive data. CTD will be triggered for every file. Dive data will be triggered on all allowed files.

### Modify iFileList

Add an `exclude` option for iFileList. This involves modifying the talend component.

### Harvest only public data

Simply harvest only data from files that are supposed to be public, both for CTD and dive data.

### Access modifier

Harvest all data using one index component and have a modifier against every row specifying whether the data is public or private. That is considering the talend component can tell which file it is harvesting from when the indexing happens.

More ideas?

**Comment by xhoenner** [comment]
That's correct @danfruehauf. @jonescc mentioned there is a filter option on the iNewOrModifiedFileList and iDeleteFileList components, so we could exclude files there instead.

**Comment by xhoenner** [comment]
@danfruehauf, @jonescc see if that's been correctly implemented.

**Comment by jonescc** [comment]
Looks like the filter expression won't help.  Its a like expression that is applied to the url.   So will need to use one of the other options?

**Comment by xhoenner** [comment]
How about something like that for the context group instead then?

```sql
WHERE url LIKE ('%ct91.mdb') or url LIKE ('%ct101.mdb') or url LIKE ('%ct110.mdb')
```

**Comment by jonescc** [comment]
No its a simple string expression used in a like.

An alternative is to use a setglobalvar component to evaluate whether you want to harvest the dive data and a run if trigger from it to run dive harvest subjob

**Comment by danfruehauf** [comment]
> An alternative is to use a setglobalvar component to evaluate whether you want to harvest the dive data and a run if trigger from it to run dive harvest subjob

I like that idea. How difficult/easy is that? Can it operate on an environment variable?

**Comment by jonescc** [comment]
Yes.  I've just shown @xhoenner how to do it.

**Comment by xhoenner** [comment]
thanks @jonescc, ready for testing @danfruehauf

**Comment by danfruehauf** [comment]
> Yes. I've just shown @xhoenner how to do it.

Is it an environment variable I can set from the command line before I trigger the harvester?

**Comment by xhoenner** [comment]
Yes it is, it uses a context parameter that you can externalise (context.exclude).

**Comment by xhoenner** [comment]
Thanks @jonescc, I made those changes.

**Comment by danfruehauf** [comment]
Hang on? Merged? Why? I haven't tested it yet...

**Pull request merged**
