### PR TITLE
Marvl aims ctd

### PR DESCRIPTION
**Pull request by lbesnard**

### CODE REVIEW

**Comment by lbesnard** [comment]
@bpasquer  I have some compilation issues :
```
Caused by: java.lang.Error: Unresolved compilation problems: 
	Type mismatch: cannot convert from Double to Float
	Type mismatch: cannot convert from String to Float
	Type mismatch: cannot convert from Float to Double
	Type mismatch: cannot convert from Float to Double
	The method makePoint(Double, Double, String) in the type ArgoUtils is not applicable for the arguments (Float, Float, String)
```

**Comment by bpasquer** [comment]
Yes , I made changes this morning  that i haven’t pushed yet
On 12 May 2015, at 12:14 pm, lbesnard <notifications@github.com<mailto:notifications@github.com>> wrote:


@bpasquer<https://github.com/bpasquer> I have some compilation issues :

Caused by: java.lang.Error: Unresolved compilation problems:
    Type mismatch: cannot convert from Double to Float
    Type mismatch: cannot convert from String to Float
    Type mismatch: cannot convert from Float to Double
    Type mismatch: cannot convert from Float to Double
    The method makePoint(Double, Double, String) in the type ArgoUtils is not applicable for the arguments (Float, Float, String)


—
Reply to this email directly or view it on GitHub<https://github.com/aodn/harvesters/pull/223#issuecomment-101100053>.

Dr. Benedicte Pasquer - Project Officer
Monday - Friday 9am -3pm
IMOS e-Marine Information Infrastructure
University of Tasmania
Ph: +61 3 6226 1927













University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by bpasquer** [comment]
MAde the required changes and corrected the datafiles. Grap the corrected ones from my home dir please

**Comment by bpasquer** [comment]
The data are now under /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/AIMS_CTD/

**Comment by lbesnard** [comment]
exception while processing this file :
/mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/AIMS_CTD/SCTmet01-2.csv
```
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1011)
```

I'm having a look why

**Comment by lbesnard** [comment]
I just rebased your 4 commits into 1. 

* did some modification regarding the deletion of data. TpostgresRow was handling the connection within it's own component, therefor tpostjob could not be used, and I think it was a good practise to add it to make sure the DB is behaving properly. Tested alright on my machine

* I moved the file SCTmet01-2.csv since it doesn't have any Water Depth values from row 8909 to 8940. Now located at : /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/badfile_aims_SCTmet01-2.csv

will deploy to RC

**Pull request merged**
