### PR TITLE
ANMN_ADCP_TIMESERIES metadata

### PR DESCRIPTION
**Pull request by lbesnard**
* add metadata spatial component

### CODE REVIEW

**Comment by mhidas** [comment]
@lbesnard You need to add the Metadata context group to the main job (ANMN_velocity_timeseries_harvester_1.0).

**Comment by lbesnard** [comment]
done, can be merged

**Comment by mhidas** [comment]
@lbesnard I don't see any additional commits here .. so how did you do it?

**Comment by mhidas** [comment]
Ah, did you change the commit that was already there? Doing a git pull on this branch resulted in several merge conflicts, even though I hadn't made any changes myself.

**Comment by lbesnard** [comment]
just did a git merge of the two last commit :
git rebase -i HEAD~2
squash the second one and keep the first one, 
ammend the commit message
git push -f origin __branchName__ 

git log to check before pushing ! really careful  since if you force to master, it could be really bad. 

Just recheck out this branch

**Comment by mhidas** [comment]
Thanks @lbesnard . That looks better, but you still have the "Implicit tContextLoad" enabled in each subjob. These should be disabled.
Also, in `UpdateMetadata` you have "Stats & Logs" set up to write into `context.logDir`, which doesn't exist in that subjob.

**Comment by lbesnard** [comment]
@mhidas I didn't write this harvester, just adding the update component

**Comment by mhidas** [comment]
@lbesnard Sorry, I wasn't accusing you of making mistakes, just asking you to fix them. While I'm looking at it, I may as well fix them myself.

**Comment by mhidas** [comment]
@lbesnard @ggalibert Please deploy when you can.

**Comment by ggalibert** [comment]
I'm on the re-deployment and created a pull request : https://github.com/aodn/chef-private/pull/1393

By the way @mhidas I got an idea for your git avatar ;-) :

midas-logo-300x225

**Comment by bpasquer** [comment]
:+1:

**Comment by ggalibert** [comment]
Deploy on RC looked good so I merged to production and should be deployed at 5pm

**Comment by mhidas** [comment]
Thanks @ggalibert . 

I'll be sure to take your avatar suggestion into consideration :)

**Pull request merged**
