### PR TITLE
AATAMS ACOUSTIC REPORTING - Ticked the box in iUpdateSpatialExtent to always update

### PR DESCRIPTION
**Pull request by xhoenner**
This change will fix the issue highlighted below. @danfruehauf please re-deploy ASAP.

Exception in component iUpdateSpatialExtent_1
org.postgresql.util.PSQLException: ERROR: relation "dw_aatams_acoustic.indexed_file" does not exist
  Position: 36
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:302)
        at aatams_acoustic_reporting.updatemetadata_0_1.UpdateMetadata.iUpdateSpatialExtent_1Process(UpdateMetadata.java:466)
        at aatams_acoustic_reporting.updatemetadata_0_1.UpdateMetadata.runJobInTOS(UpdateMetadata.java:843)
        at aatams_acoustic_reporting.updatemetadata_0_1.UpdateMetadata.runJob(UpdateMetadata.java:690)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_5Process(aatams_acoustic_harvester.java:2453)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_2Process(aatams_acoustic_harvester.java:2334)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_4Process(aatams_acoustic_harvester.java:2162)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_1Process(aatams_acoustic_harvester.java:1990)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.iPostgresqlDbUpdate_1Process(aatams_acoustic_harvester.java:1818)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.runJobInTOS(aatams_acoustic_harvester.java:4259)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.main(aatams_acoustic_harvester.java:4051)
Exception in component tRunJob_5
java.lang.RuntimeException: Child job running failed
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_5Process(aatams_acoustic_harvester.java:2464)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_2Process(aatams_acoustic_harvester.java:2334)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_4Process(aatams_acoustic_harvester.java:2162)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_1Process(aatams_acoustic_harvester.java:1990)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.iPostgresqlDbUpdate_1Process(aatams_acoustic_harvester.java:1818)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.runJobInTOS(aatams_acoustic_harvester.java:4259)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.main(aatams_acoustic_harvester.java:4051)
finish;2015-09-21 23:13:33+10:00 759 minutes

### CODE REVIEW

**Comment by danfruehauf** [comment]
@xhoenner I'll deploy that for you.

**Comment by xhoenner** [comment]
@danfruehauf awesome, thanks!

**Comment by danfruehauf** [comment]
@xhoenner Running now.

The beers on @lbesnard 's desktop are getting warmer...

**Comment by xhoenner** [comment]
@danfruehauf great thanks! Hopefully this time it will work.

> The beers on @lbesnard 's desktop are getting warmer...

And they're down to 4 now, I'm extremely concerned.

**Comment by xhoenner** [comment]
@danfruehauf succeeded on rc, can you promote it to prod please?

**Comment by danfruehauf** [comment]
@xhoenner Yep. Leave it with me.

**Comment by xhoenner** [comment]
@danfruehauf, Laurent has done that already, doesn't he deserve his 6 pack?

**Comment by danfruehauf** [comment]
@xhoenner By accident I promoted to prod an older version, but noticed that and deleted it. All good.

**Pull request merged**
