### PR TITLE
Create aodn nt sattag oliveridley

### PR DESCRIPTION
**Pull request by xhoenner**
New harvester, similar to aodn_nt_sattag_hawksbill as same data provider. New schema and data bags needed.

UUID of metadata records correct in harvester.
SourceDir should point to /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/nt_sattag_oliveridley

### CODE REVIEW

**Comment by lbesnard** [comment]
onto it

**Comment by lbesnard** [comment]
Remarks :
You basically have to different order by in your views :
``` sql
ORDER BY m.device_id, timezone('UTC'::text, m."timestamp"), m.pressure;
ORDER BY m.device_id, timezone('UTC'::text, m.timestamp_start);
```

But your indexes are on 
 * geom
 * device_id,  timezone('UTC'::text, "timestamp"), pressure

One index is missing which should be on device_id,  timezone('UTC'::text, "timestamp")

such as 
```sql
CREATE INDEX measurements_idx_dev_time
  ON aodn_nt_sattag_oliveridley.measurements
  USING btree
  (device_id COLLATE pg_catalog."default", timezone('UTC'::text, "timestamp"));
```


One last thing regarding context.metadata_file = /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/nt_sattag_oliveridley/oliveridley_turtle_metadata.csv
which relies actually on sourceDir,

why not doing in tfileInputDelimited put :
```
context.sourceDir + "/" + context.metadata_file
```
in the filename stream ? By creating context.metadata_file in Metadata_Harvest subjob. This facilitates heaps the creation of databags

**Comment by xhoenner** [comment]
@lbesnard I made the change you requested regarding the context.metadata_file, thanks for pointing that out.

> all good otherwise, just have some warnings.

I also get these warnings but I don't think there's anything that can be done about that. It doesn't impact the integrity of the data nor the harvester.

**Comment by lbesnard** [comment]
I have the feeling this won't work, as context.metadata_file will probably a NULL value after talking with @anguss00 . I think it has to be defined differently. I'll show you what I mean on monday. please remind me

**Comment by xhoenner** [comment]
@lbesnard done the changes you requested, let me know if that suits you.

**Comment by lbesnard** [comment]
@xhoenner I created a new branch merging all your commits into one and merged it to master. I didn't want to do it on this one in case you last commit won't work with the databags thing. So you wouldn't have to work on it again, and I could just remove this last commit, ... anyway. I'll delete this branch once the harvester will have run successfully on RC

**Comment by xhoenner** [comment]
@lbesnard the harvester failed on 14-nsp, here's a copy of the logs, looks like it's due to the metadata file. Any idea what needs to be done?

Exception in component tFileInputDelimited_1
java.io.FileNotFoundException: /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/oliveridley_turtles_nt/null (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at aodn_nt_sattag_oliveridley.metadata_harvest_0_1.Metadata_Harvest.tFileInputDelimited_1Process(Metadata_Harvest.java:1868)
        at aodn_nt_sattag_oliveridley.metadata_harvest_0_1.Metadata_Harvest.runJobInTOS(Metadata_Harvest.java:3292)
        at aodn_nt_sattag_oliveridley.metadata_harvest_0_1.Metadata_Harvest.runJob(Metadata_Harvest.java:3159)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.tRunJob_3Process(aodn_nt_sattag_oliveridley_harvester.java:2395)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.iPostgresqlDbUpdate_1Process(aodn_nt_sattag_oliveridley_harvester.java:2254)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.iIndexFiles_1_iFilesProcess(aodn_nt_sattag_oliveridley_harvester.java:4458)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.tPostgresqlConnection_1Process(aodn_nt_sattag_oliveridley_harvester.java:1584)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.runJobInTOS(aodn_nt_sattag_oliveridley_harvester.java:6286)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.main(aodn_nt_sattag_oliveridley_harvester.java:6010)
Exception in component tRunJob_3
java.lang.RuntimeException: Child job running failed
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.tRunJob_3Process(aodn_nt_sattag_oliveridley_harvester.java:2406)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.iPostgresqlDbUpdate_1Process(aodn_nt_sattag_oliveridley_harvester.java:2254)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.iIndexFiles_1_iFilesProcess(aodn_nt_sattag_oliveridley_harvester.java:4458)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.tPostgresqlConnection_1Process(aodn_nt_sattag_oliveridley_harvester.java:1584)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.runJobInTOS(aodn_nt_sattag_oliveridley_harvester.java:6286)
        at aodn_nt_sattag_oliveridley.aodn_nt_sattag_oliveridley_harvester_0_1.aodn_nt_sattag_oliveridley_harvester.main(aodn_nt_sattag_oliveridley_harvester.java:6010)
finish;2015-05-18 17:08:09+10:00 0 minutes

**Comment by lbesnard** [comment]
yeap yeap I know. I was working on this yesterday

**Pull request closed without merging**
