### PR TITLE
ABOS_CURRENTS: handle missing timestamp attributes

### PR DESCRIPTION
**Pull request by mhidas**
Some files are missing global attributes like `time_deployment_start` etc... and have been crashing the harvester. This will just quietly set them to null.

### CODE REVIEW

**Comment by ggalibert** [comment]
Deployed to RC.

**Comment by mhidas** [comment]
Thanks @ggalibert!

**Comment by mhidas** [comment]
@ggalibert Could you please deploy it to prod too? I've tested it in RC and it's good to go.

**Comment by danfruehauf** [comment]
@mhidas Will be deployed soon.

**Pull request merged**
