### PR TITLE
New map views created by ANMN_METADATA harvester

### PR DESCRIPTION
**Pull request by mhidas**
* add a data_mode column in `moorings_all_map` to be used as a filter
* update boolean columns in `moorings_all_map` to use `LIKE` instead of regex matching to speed up the query
* create new views for `abos_sots_dm_map` and `abos_sots_rt_map`

### CODE REVIEW

**Comment by mhidas** [comment]
All the changes can be seen in the [changelog](https://github.com/aodn/harvesters/pull/558/files#diff-6b8d31234384ef8b852b0a9099298376) (i.e. nothing else has been changed in Talend)

**Comment by mhidas** [comment]
@lbesnard @bpasquer @xhoenner Would one of you mind having a quick look at this today? I'd like to get it into RC to test & demo this week.

**Comment by bpasquer** [comment]
All good @mhidas

**Comment by mhidas** [comment]
@bpasquer Thanks!

**Pull request merged**
