### PR TITLE
ABOS_SOFS_SURFACE_FLUXES: fix missing fileId context

### PR DESCRIPTION
**Pull request by mhidas**
@lbesnard I hope this will fix the errors in RC. Please test.

### CODE REVIEW

**Comment by lbesnard** [comment]
@mhidas funny, I did the modification, but it almost look that its you who did it. wanna have a look and merge ?

**Comment by lbesnard** [comment]
@mhidas can you please review and merge so I can build it on jenkins and run it asap on nsp14 ? cheers

**Comment by mhidas** [comment]
@lbesnard We're getting there... you fixed the issues you pointed out in #200, but then shouldn't `fileId` have the same type in the `DeleteSOFSFileData` subjob?

Also, `fileId` should actually be of Long type, according to the type of the `file_id` column that gets its value from `fileId`. In that case, do you still need intValue() ?

**Comment by lbesnard** [comment]
> Also, fileId should actually be of Long type, according to the type of the file_id column that gets its value from fileId. In that case, do you still need intValue() ?

it makes sense (if I understood properly). Didn't get any error tho, so maybe talend does some type conversion on its own

> shouldn't fileId have the same type in the DeleteSOFSFileData subjob?

will have a look

**Comment by lbesnard** [comment]
@mhidas  done your suggestions (both)

**Comment by lbesnard** [comment]
@mhidas  FYI :
```In Java, the language itself determines how the certain types are represented. The order is: byte 8 bits, short 16 bits, int 32 bits, long 64 bits. In Java, all types are signed, there are no unsigned versions.Feb 21, 2013```

And
http://stackoverflow.com/a/15005226/4294174


In other words, 2^32 = 4294967296 for unsigned values. I think we're safe to use INT as a type in java before going over the limit of files to harvest.

**Comment by mhidas** [comment]
@lbesnard My point was mainly about being consistent with the database. However I've just realised that even though the `file_id` columns in the `measurement` and `file_metadata` tables in the db are of type "bigint", the `id` they point to in `indexed_file` is only "int" anyway. So all I can say now is "Whatever...."

**Comment by lbesnard** [comment]
@mhidas  can this be reviewed/merged please so I can deploy it ? cheers

**Comment by lbesnard** [comment]
thx. will deploy

**Pull request merged**
