### PR TITLE
new NRMN harvester

### PR DESCRIPTION
**Pull request by ana-berger**

### CODE REVIEW

**Comment by bpasquer** [comment]
A couple of comments so far:

- in the Job iPostgresDBUpdate_1:the column `geom` is missing from the declaration for table Species_list

-  geom column are missing in all tPostgresqlOutput component, meaning that geom  values  are not harvested into target _map tables

**Comment by ana-berger** [comment]
> A couple of comments so far:
> 
> * in the Job iPostgresDBUpdate_1:the column `geom` is missing from the declaration for table Species_list

so, this table does not have lat & lon data, should it have geom anyway?

> * geom column are missing in all tPostgresqlOutput component, meaning that geom  values  are not harvested into target _map tables

I am not sure it is the same thing or related, but we talked about adding the geom column in geoserver, from what I remember. We will talk about it.

Thanks Bene!

**Comment by bpasquer** [comment]
> so, this table does not have lat & lon data, should it have geom anyway?

Yes, you're right, ignore this comment

**Comment by ana-berger** [comment]
I made the changes; hope I did not forget anything

**Pull request merged**
