### PR TITLE
Publish AODN_CSIRO_CMAR data

### PR DESCRIPTION
**Pull request by xhoenner**
New harvester to get all CSIRO data (i.e. ADCP, CTD, hydrology, mooring, trajectory, underway, and XBT data) into our database as part of AODN and MARVL3 projects.

New schema and data bags are required. The person in charge of deploying this harvester will need to get the UUID for the different metadata records from me (haven't asked Nat yet to create those).

Needs to be reviewed ASAP as those datasets will be required for MARVL. The data is available on 10-nsp:/mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/CSIRO_CMAR

### CODE REVIEW

**Comment by bpasquer** [comment]
i feel privileged. thank you @xhoenner

**Comment by xhoenner** [comment]
ADCP: uuid=5ac7261a-5f73-4795-a13f-06093471a517
CTD: uuid=42887b08-8839-4f42-9621-cdf3b0ef15db
Hydrology: uuid=0cbba999-2e5a-49f4-bcac-373fa8694ceb
Mooring: uuid=e6ac3eba-a732-4772-9f5e-03c801380e0d
Trajectory: uuid=f4b7f0bb-e1e8-48fb-9cf9-3e0b492c1496
Underway: uuid=de696486-3c87-4046-b625-259668beea49
XBT: uuid=fb63d0c8-c454-40de-a8b0-88eb1c295948

**Comment by bpasquer** [comment]
just two comments:
-you've left what in think are relics from a previous harvester in the context of job UpdateMetadata( namely metadata_*_Haulout)
-File delimited metadata: schema for hydrology and ctd are not used in the respective tfileInputDelimited components. Not sure why.

**Comment by xhoenner** [comment]
@bpasquer I made the changes you requested.

**Comment by bpasquer** [comment]
seems like something didn't quite work cause i'm still seeing the old context in UpdateMetadata

**Comment by xhoenner** [comment]
@bpasquer You're right it was still in the main job, should be all good now. Thanks Bene

**Comment by bpasquer** [comment]
found another tiny detail : in job HarvestTrajectory Data: component tfileInputDelimited : probably better to use property type from repo .

**Comment by xhoenner** [comment]
@bpasquer you've said it yourself, it's a tiny detail. I think you've been picky enough on this one. It runs fine and outputs the data properly, making the change you suggest won't affect the harvester.

**Pull request merged**
