### PR TITLE
FAIMMS - fix time coverage

### PR DESCRIPTION
**Pull request by lbesnard**
* issue with *._map having wrong value of time_start and time_end for a
   channel_id. Value was taken from last file added, and not from all
   channel. This is now fixed
 * also created an update query to fix already processed channels

### CODE REVIEW

**Comment by lbesnard** [comment]
@xhoenner this should fix the issue in reporting

**Comment by danfruehauf** [comment]
@lbesnard @xhoenner Any of you can trigger it with:
```
$ talend_liqui faimms-faimms
```

This will trigger the harvester liquibase migrations.

**Comment by lbesnard** [comment]
@danfruehauf already done

**Comment by lbesnard** [comment]
def a good thing to have created this function !

**Pull request merged**
