### PR TITLE
feat: anmn_metadata new dwm_csiro_*_map

### PR DESCRIPTION
**Pull request by evacougnon**

### CODE REVIEW

**Review by mhidas — COMMENTED** [review]
From what I can tell looking at just the XML (I haven't opened Talend in years...) it looks good, but I think there might be something missing - there was a small bit of SQL in the data harvest and delete subjobs that should be modified to set `DwmCsiroGriddedHourlyUpdated` to `true`, otherwise the harvester won't know when to update the spatial extent...

**Comment by mhidas** [comment]
You had it in your previous PR:
https://github.com/aodn/harvesters/blob/060e5a499e4689a9560d925b85f4848197b8fb09/workspace/ANMN_METADATA/process/subjob/HarvestFileSystemMetadata_0.1.item#L889

**Comment by evacougnon** [comment]
Good pick @mhidas thanks, it should have been part of the PR, I'm looking into it now

**Review by mhidas — APPROVED** [review]
:+1: Looks good now, as far as I can tell without opening the harvester in Talend :grin:

**Pull request merged**
