### PR TITLE
WODB harvester

### PR DESCRIPTION
**Pull request by bpasquer**
@xhoenner : this one is for you. Boring but simple.

### CODE REVIEW

**Comment by xhoenner** [comment]
@bpasquer I won't have time to review your harvester before Friday, is that alright?

**Comment by bpasquer** [comment]
then i guess i'll have to pick another victim. @lbesnard ?

**Comment by bpasquer** [comment]
Hold on @lbesnard , I have to make changes tomorrow morning

**Comment by bpasquer** [comment]
Now ready to be reviewed @lbesnard  
Harvester only harvests metadata and data. No wms or wfs needed are needed for this dataset.

**Comment by lbesnard** [comment]
@bpasquer could you please put the files somewhere on nsp?

**Comment by bpasquer** [comment]
@lbesnard :it’s in my home dir: /home/bpasquer/WOD_datafiles/
ihave chage the  files ownership so you should be able to play with them

**Comment by lbesnard** [comment]
you need to make the dir executable for group.  chmod -R 755 WOD_datafiles

**Comment by lbesnard** [comment]
Run well on my machine

Context :
Database -> Destination

Good job Cobra !

**Pull request merged**
