### PR TITLE
ANMN_NRS_CTD_PROFILES: update source context to include regional sites

### PR DESCRIPTION
**Pull request by mhidas**
We have profile data that are not part of NRS. We need to harvest them too.

### CODE REVIEW

**Comment by mhidas** [comment]
@lbesnard @ggalibert This actually just needs a databag update. See the diff of context/source_0.1.item for the change required.

**Comment by lbesnard** [comment]
@mhidas, in the futurem no need really to create a harvester PR for a databag change

**Comment by mhidas** [comment]
@lbesnard Yep, I realise that. I just thought it's best to keep the values of the context variables in the harvester in sync with what they will be in production (to the extent possible).

**Comment by lbesnard** [comment]
databags updated btw

**Comment by mhidas** [comment]
@lbesnard Thanks. When will this change be deployed to RC/prod?

**Comment by lbesnard** [comment]
@mhidas  just saw your msg now. Well as soon as I updated the bags, so 8 days ago

**Pull request merged**
