### PR TITLE
Modify AATAMS_ACOUSTIC_REPORTING to harvest QC'd detection data

### PR DESCRIPTION
**Pull request by xhoenner**
* Modifications to harvest content of QC'd csv files
  * Added components to harvest metadata
  * More changes
  * Liquibase for _data and _metadata, built _map query
  * Finalise harvester
  * Convert harvester to manifest harvesting components

Data bags need to be updated. The metadata record already exists on catalogue-rc [here](https://catalogue-rc.aodn.org.au/geonetwork/srv/en/metadata.show?uuid=0ede6b3d-8635-472f-b91c-56a758b4e091) with the UUID in the Metadata context group being the one to use for the corresponding data bag. 

A pipeline needs to be set up to harvest the ~3500 .csv data files and .txt metadata file @smancini. I've put up some sample files on [CloudStor](https://cloudstor.aarnet.edu.au/plus/index.php/s/S4hjQgInTr1JVZv).

### CODE REVIEW

**Comment by bpasquer** [comment]
Job Populate_layers:  tick "die on error" in tfileInputDelimited

Surprisingly, all of the following have the same issue with the property type being set to built-in instead of "from repository"  Maybe when i  opened the harvestser i reset the property to built-in. Anyway, better checkeck whether the box is ticked off...
Job populate_layers: iUpdateIndex , iDeletedFileList, tPostgresqlRow,iNewOrModifiedFileList: 
Job Harvest_data: TPostgresqlConnection

**Comment by xhoenner** [comment]
Changes done @bpasquer, thanks for your help.

**Comment by bpasquer** [comment]
My pleasure. I was hoping to get a taste of the snail but didn't have the opportunity. Maybe next time...

**Comment by xhoenner** [comment]
how voracious of you!

**Pull request merged**
