### PR TITLE
Remove reference to old version of netcdf library - talend can pick i…

### PR DESCRIPTION
**Pull request by jonescc**
…t up from installed components

Most likely cause for https://github.com/aodn/harvesters/issues/504 and https://github.com/aodn/harvesters/issues/501.

### CODE REVIEW

**Comment by jonescc** [comment]
@bpasquer - can you review this?  If we build anfog_rt again without this fix, we'll end up with issues like #504 and #501 again.

**Comment by bpasquer** [comment]
Hold on Craig, are you fixing ANFOG_DM or ANFOG_RT or both?

**Comment by jonescc** [comment]
ANFOG_RT includes an old version of the netcdf java library.  This was recently built in jenkins causing the old version of the netcdf java library to be copied to the harvester build library.  ANFOG_DM and AODN_RAN_CTD were then built in jenkins and the old version of the library was copied from the harvester build library along with the required version.   This then caused #504 and #501.  So not fixing ANFOG_DM but stopping ANFOG_RT from causing similar issue in future.

**Comment by bpasquer** [comment]
ok, i see

**Comment by bpasquer** [comment]
It solved the issue on the PO box.  Could you please deploy on RC @lbesnard

**Comment by lbesnard** [comment]
will be deployed on RC at lunch

**Pull request merged**
