### PR TITLE
ARGO - fix empty view for reporting

### PR DESCRIPTION
**Pull request by lbesnard**
* the pipeline transition made some views used for reporing only empty.
   this concerned platform_metadata_current best_cycle_location
 * a LQ statement was also 'misplaced' making the start of the Argo from
   a new schema impossible without errors. The modification was tested
   against a new schema, as well as a backup of what was currently on
   production without any issues

### CODE REVIEW

**Comment by xhoenner** [comment]
Ready to be deployed @danfruehauf

**Comment by xhoenner** [comment]
looks like it hasn't been deployed, @jonescc would you mind deploying this new version of the Argo harvester on rc?

**Comment by jonescc** [comment]
OK.  I think I've deployed the updated harvester to RC - its been a while.   Let me know if that's not the case.

**Comment by xhoenner** [comment]
@jonescc looks good on Jenkins, I'll run the harvester on rc.

**Comment by xhoenner** [comment]
@jonescc it ran successfully on 14-nsp but there's only one row in both the `argo.argo_float` and `argo.platform_metadata_current` views whereas there used to be thousands.

**Comment by xhoenner** [comment]
my bad @jonescc it's still the old version of the harvester that I ran, needs to be tested tomorrow.

**Comment by xhoenner** [comment]
@lbesnard, @jonescc got the following error when running the harvester on 14-nsp


Exception in component iUpdateIndex_1
java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at java.io.FileReader.<init>(FileReader.java:58)
        at au.org.emii.talend.updateindex.Component.run(Component.java:29)
        at argo.argo_harvester_0_1.Argo_harvester.iUpdateIndex_1Process(Argo_harvester.java:1162)
        at argo.argo_harvester_0_1.Argo_harvester.runJobInTOS(Argo_harvester.java:3814)
        at argo.argo_harvester_0_1.Argo_harvester.main(Argo_harvester.java:3610)
finish;2015-12-15 17:08:46+11:00 0 minutes

**Comment by jonescc** [comment]
Sounds like it can't read the manifest file

**Comment by xhoenner** [comment]
@lbesnard could you then please modify the data bags accordingly?

**Comment by jonescc** [comment]
@xhoenner, as discussed - looks to me like argo runs as a pipeline process so specifying manifest file names in databags is not what is required here.

I kicked off an argo rsync on 14-nsp for a limited set of argo data, it looks like the updated harvester has been run now and the reporting views look to have been updated.   Might be worth someone verifying that the reporting views reflect the profiles harvested to that instance.

**Comment by xhoenner** [comment]
thanks @jonescc, the reporting views are now consistent with the content of the latest Argo data report. Could you please promote this harvester to production on Jenkins?

**Comment by jonescc** [comment]
@xhoenner, looks like @lbesnard has already promoted it.

**Comment by xhoenner** [comment]
Looks like he did yes, however the last time the Argo harvester ran on 10-nsp was on 25 Oct. @jonescc Could you trigger it manually on 10-nsp like you did on 14-nsp?

**Comment by jonescc** [comment]
@xhoenner, you must be looking at the non-pipelline logs.  The argo pipeline harvester is triggered by the rsync from ifremer which runs every Friday after 6pm, so should run tonight.

**Comment by xhoenner** [comment]
Well I just run the following on 10-nsp: talend_version argo-argo. I am not aware of any other way to check the log of harvesters.

**Comment by xhoenner** [comment]
Looking at the argo.argo_float view, there are a lot of fields in that view for which we used to have information (*e.g.* last_measure_date, last_location) that are now empty. It'd be great to have that information back for each float, could you please look into that @jonescc?

**Comment by jonescc** [comment]
Not without reverting to using trajectory files which were never kept up to date.   Spoke to @smancini about this years ago now and he was OK with that.

**Comment by jonescc** [comment]
Actually, I was thinking of the descent start and ascent end date on float_cycle which was sourced from the trajectory file.  Not sure why the fields on the argo_float view are empty although I suspect it happened at the same time and is probably related .  Can probably be sourced in other ways now.

Perhaps @lbesnard can look at that - I don't maintain that harvester anymore.  Or needs to be added as a VIT or backlog item for the development team to look at.

**Comment by xhoenner** [comment]
Most of the info missing info comes from the profile_general_current view, wouldn't the following query solve the present issue?
 
``` sql
 SELECT file.url,
    file.modified,
    profile.file_id,
    profile.profile_no,
    profile.platform_number,
    profile.project_name,
    profile.pi_name,
    profile.cycle_number,
    profile.direction,
    profile.data_centre,
    profile.dc_reference,
    profile.data_state_indicator,
    profile.data_mode,
    profile.inst_reference,
    profile.wmo_inst_type,
    profile.juld,
    profile.juld_qc,
    profile.juld_location,
    profile.latitude,
    profile.longitude,
    profile.position_qc,
    profile.positioning_system,
    profile.profile_pres_qc,
    profile.profile_temp_qc,
    profile.profile_psal_qc,
    profile.profile_doxy_qc,
    profile.profile_temp_doxy_qc
   FROM argo.profile_general profile
     JOIN argo.indexed_file file ON file.id = profile.file_id AND NOT file.deleted
```

**Comment by jonescc** [comment]
Yes, that would do it.

**Pull request merged**
