### PR TITLE
PLANKTON_PRODUCTS: migration to Talend 7

### PR DESCRIPTION
**Pull request by mhidas**

### CODE REVIEW

**Comment by mhidas** [comment]
@jonescc Here you go

**Comment by jonescc** [comment]
Doesn't look to me like the pom directory is actually required - its generated whenever I open the job.

**Comment by mhidas** [comment]
Ok, I've removed poms and added these directories to .gitignore (along with temp)

**Comment by mhidas** [comment]
Thanks @jonescc . FYI this has been deployed to RC and runs just fine.

**Pull request merged**
