### PR TITLE
ANMN_ACIDIFICATION_NRT metadata

### PR DESCRIPTION
**Pull request by lbesnard**
* add metadata spatial component

### CODE REVIEW

**Comment by mhidas** [comment]
@lbesnard You need to add the Metadata context group to the contexts for the main job. Otherwise I don't think the values set up in the databags will be read in and passed to the UpdateMetadata subjob.

**Comment by lbesnard** [comment]
@jonescc  I actually never know how contexts are handled by Talend. Is what @mhidas says right or not ?

**Comment by mhidas** [comment]
@lbesnard See Craig's description in the [Google Doc](https://docs.google.com/document/d/1-E05wDMvI_Yy2Zz9m3D8DCWUjjkhPDJFm_jr9TvbUgc/edit#heading=h.onsdd540oals)

Top of page 29: "Add the Metadata context group to the context variables used by the main harvester job"

**Comment by mhidas** [comment]
Also don't forget to tick "Transmit whole context" for each subjob!

**Comment by lbesnard** [comment]
done. can be merged

**Comment by lbesnard** [comment]
@mhidas .

**Comment by mhidas** [comment]
The UpdateMetadata subjob had "use project settings" selected for load context and logging, which I don't think we want (not sure what the project settings are). I've de-selected these now, so all good.

**Comment by mhidas** [comment]
@lbesnard @ggalibert Please deploy when you can.

**Comment by lbesnard** [comment]
Im onto it

**Comment by lbesnard** [comment]
@mhidas , please look at the log files on nsp14 once the harvester will have run successfully, and i'll push it to prod

**Comment by mhidas** [comment]
@lbesnard The harvester ran ok last night, but it doesn't look like it's been updated! There's  no output from the UpdateMetadata component in the log, and the java/build.properties file says GIT_COMMIT=6c7710 which was in September.

**Comment by lbesnard** [comment]
@anguss00 nsp14 still shows the same commit

**Comment by lbesnard** [comment]
@mhidas the harvester is curretly running on nsp14. Please look at the log when done

**Comment by lbesnard** [comment]
log is good. I'll merge to prod

**Comment by lbesnard** [comment]
done

**Comment by mhidas** [comment]
Great! Thanks @lbesnard

**Pull request merged**
