### PR TITLE
ANFOG_dM : add processing of NRL Adapter missions

### PR DESCRIPTION
**Pull request by bpasquer**

### CODE REVIEW

**Comment by lbesnard** [comment]
@bpasquer what shall we do with this one ?

**Comment by bpasquer** [comment]
Actually, I can close it now. We've been waiting for some metadata to push this in prod, but  the anfog version 2 pipeline is nearly ready,  there's no point adding this in V1

**Comment by bpasquer** [comment]
Reopening as I thought i was in data-services repo( where the PR for the NRL adaper file should be closed). This one can remain open until we get the metadata I was talking about

**Comment by bpasquer** [comment]
Closing this PR as a new one integrating latest changes in ANFOG_DM harvester will solve the conflicts

**Pull request closed without merging**
