### PR TITLE
SOOP TRV - modify data view - FIX: order by not on index

### PR DESCRIPTION
**Pull request by lbesnard**
very basic PR. modified the order by in the _data layer to use ```  ORDER timezone('UTC'::text, measurements_merged_data."TIME");``` where there is an index on rather than ```"TIME".

```sql
<changeSet author="talend" id="data_view" runOnChange="true">
        <sql>
           DROP VIEW IF EXISTS soop_trv_trajectory_data;
CREATE OR REPLACE VIEW soop_trv_trajectory_data AS 
SELECT measurements_merged_data.trip_id, 
visualisation_wms.vessel_name,
timezone('UTC'::text, measurements_merged_data."TIME") AS "TIME", 
measurements_merged_data."LATITUDE", 
measurements_merged_data."LONGITUDE", 
measurements_merged_data."TURB", 
measurements_merged_data."TEMP", 
measurements_merged_data."PSAL", 
measurements_merged_data."CPHL", 
measurements_merged_data."TURB" IS NOT NULL AS "TURB_b", 
measurements_merged_data."TEMP" IS NOT NULL AS "TEMP_b",
measurements_merged_data."PSAL" IS NOT NULL AS "PSAL_b",
measurements_merged_data."CPHL" IS NOT NULL AS "CPHL_b", 
measurements_merged_data.geom
   FROM measurements_merged_data
   JOIN visualisation_wms ON visualisation_wms.trip_id = measurements_merged_data.trip_id
  ORDER timezone('UTC'::text, measurements_merged_data."TIME");

    </sql>
 </changeSet>
```

### CODE REVIEW

**Comment by lbesnard** [comment]
@jonescc please disregard, I need to fix something

**Comment by lbesnard** [comment]
@jonescc I added a commit which improves the detection of duplicate layers. I ran out of time for testing as my stack got destroyed at 7pm sharp. 
Anyway, my issue was that the harvester was not triggering for some reason the file I got it to harvester. Doing the same thing as usual with the fileList. The file was not registered in the indexed-file table.

that is was my input file as an example:
https://s3-ap-southeast-2.amazonaws.com/imos-data/IMOS/SOOP/SOOP-TRV/VNCF_Cape-Ferguson/By_Cruise/Cruise_START-20090214T204718Z_END-20090228T012147Z/temperature/IMOS_SOOP-TRV_T_20090214T204718Z_VNCF_FV01_END-20090228T012147Z.nc

**Comment by lbesnard** [comment]
@jonescc I'm having some severe issues with this harvester now. I can't seem to harvest any file anymore. The indexed_file table remains totally empty

Here is my context definition
```
context.fileList = /vagrant/src/tmp/fileList
context.base = null
```

with the fileList containing the following file (which can be downloaded [here](https://s3-ap-southeast-2.amazonaws.com/imos-data/IMOS/SOOP/SOOP-TRV/VNCF_Cape-Ferguson/By_Cruise/Cruise_START-20090214T204718Z_END-20090228T012147Z/temperature/IMOS_SOOP-TRV_T_20090214T204718Z_VNCF_FV01_END-20090228T012147Z.nc))
```
cat /vagrant/src/tmp/fileList
$ /vagrant/src/tmp/trv/IMOS_SOOP-TRV_T_20090214T204718Z_VNCF_FV01_END-20090228T012147Z.nc
```
The harvester seems to find the file, but doesn't want to index it. See
```
FILE_INDEX_UPDATER - WARNING: /vagrant/src/tmp/trv/IMOS_SOOP-TRV_T_20090214T204718Z_VNCF_FV01_END-20090228T012147Z.nc not found on indexINFO 
```

I don't quite get what could be the issue. I tried swapping the first two components of the main job without any success:



The full log output is:
```
Starting job SOOP_TRV_harvester at 12:28 21/05/2020.

[statistics] connecting to socket on port 3342
[statistics] connected
Exception in component Implicit_Context_Regex (SOOP_TRV_harvester)
java.io.FileNotFoundException: null (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.talend.fileprocess.TOSDelimitedReader.<init>(TOSDelimitedReader.java:88)
	at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.Implicit_Context_RegexProcess(SOOP_TRV_harvester.java:1023)
	at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.runJobInTOS(SOOP_TRV_harvester.java:6358)
	at soop_trv.soop_trv_harvester_0_1.SOOP_TRV_harvester.main(SOOP_TRV_harvester.java:6055)
Start of try block
tempFile_cid /tmp/talend-temp-7048875036228556131/changelog.xml
***********************
conn host:harvest-db-aodnstack-lbesnard.dev.aodn.org.au, port:5432, schema:soop_trv, name:harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory, user:soop_trv
url_cid:jdbc:postgresql://harvest-db-aodnstack-lbesnard.dev.aodn.org.au:5432/harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
schema_cid:soop_trv
userName_cid:soop_trv
INFO 5/21/20 12:28 PM:liquibase: Successfully acquired change log lock
INFO 5/21/20 12:28 PM:liquibase: Reading from soop_trv.databasechangelog
INFO 5/21/20 12:28 PM:liquibase: Reading from soop_trv.databasechangelog
INFO 5/21/20 12:28 PM:liquibase: Successfully released change log lock
***** completed finally block ***********
In finally block
INFO 5/21/20 12:28 PM:liquibase: Successfully acquired change log lock
INFO 5/21/20 12:28 PM:liquibase: Reading from soop_trv.databasechangelog
INFO 5/21/20 12:28 PM:liquibase: Reading from soop_trv.databasechangelog
INFO 5/21/20 12:28 PM:liquibase: Successfully released change log lock
FILE_INDEX_UPDATER - WARNING: /vagrant/src/tmp/trv/IMOS_SOOP-TRV_T_20090214T204718Z_VNCF_FV01_END-20090228T012147Z.nc not found on indexINFO 5/21/20 12:28 PM:liquibase: Successfully acquired change log lock
Start of try block
tempFile_cid /tmp/talend-temp-676950475319093679/changelog.xml
***********************
conn host:harvest-db-aodnstack-lbesnard.dev.aodn.org.au, port:5432, schema:soop_trv, name:harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory, user:soop_trv
url_cid:jdbc:postgresql://harvest-db-aodnstack-lbesnard.dev.aodn.org.au:5432/harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
schema_cid:soop_trv
userName_cid:soop_trv
INFO 5/21/20 12:28 PM:liquibase: Reading from soop_trv.databasechangelog
INFO 5/21/20 12:28 PM:liquibase: Reading from soop_trv.databasechangelog
INFO 5/21/20 12:28 PM:liquibase: Successfully released change log lock
***** completed finally block ***********
In finally block
* iUpdateSpatialExtent - files changed: false
* iUpdateSpatialExtent - updating spatial extent: false
[statistics] disconnected
```

**Comment by jonescc** [comment]
I'll have a quick look.

**Comment by jonescc** [comment]
OK. so when you say 

> Here is my context definition
> 
> ```
> context.fileList = /vagrant/src/tmp/fileList
> context.base = null
> ```

Is that null a String? i.e. "null"

If so, then the harvester will be looking for the file at null/vagrant/src/tmp/trv/IMOS_SOOP-TRV_T_20090214T204718Z_VNCF_FV01_END-20090228T012147Z.nc, not finding it, saying its not on the index either and doing nothing.

**Comment by jonescc** [comment]
Might be useful to log the file its trying to process for situations like this.  I'll raise an issue, but hopefully you can continue for now.

**Comment by lbesnard** [comment]
> Is that null a String? i.e. "null"

You're a blooding legend! I wrote null, expected it was understood as a Null value, but yes it was a null string. It's extremely bizarre though because the error message was not mentioning the null string in the path of the file

**Comment by lbesnard** [comment]
tested on my pipeline box, working fine. ready to be merged (@bpasquer if you re bored tomorrow :) )

**Pull request merged**
