### PR TITLE
Get rid of duplicates in AATAMS_SATTAG_DM

### PR DESCRIPTION
**Pull request by xhoenner**
Addresses https://github.com/aodn/harvesters/issues/487

### CODE REVIEW

**Comment by julian1** [comment]
hey @xhoenner notice this has a big sql delete statement in it. Would it be better to go in https://github.com/aodn/aatams-content ?

**Comment by xhoenner** [comment]
@jonescc this was merged 28 days ago (~ mid-December), however, I can't find the corresponding record on Jenkins. The last time the AATAMS_SATTAG_DM harvester was built there was on November 24.

Any idea what might have gone wrong?

**Comment by jonescc** [comment]
Not sure exactly why the build didn't trigger.  May be related to the work going on with Jenkins over the last couple of months. 

I kicked off a new build which just completed successfully.   Did you want this in RC?

**Comment by xhoenner** [comment]
Thanks @jonescc, could you promote it to prod straight away please? Those were only minor changes, and I had run the harvester against a full copy of the corresponding prod schema on my po box.

**Comment by jonescc** [comment]
OK promoted to prod.  I've deployed it to RC/should deploy to prod tonight. I'd suggest running in RC anyway - its a more controlled environment than the PO box and a better place to do pre-release testing.

**Pull request merged**
