### PR TITLE
SOOP CO2 event driven

### PR DESCRIPTION
**Pull request by lbesnard**
* remove source context, as not used anymore. Need to figure out how
   the talend harvester gets feeded with a manifest file
 * replace ALL old componenents with adequate manifest ones, as well as
   proper harvest type value
 * general cleaning/add tpostjob , merged harvestmetadata within main
   job
 * WARNING : NO TEST WAS PERFORMED AS NO MANIFEST FILE PROVIDED

### CODE REVIEW

**Comment by lbesnard** [comment]
@danfruehauf we need to test this

**Comment by danfruehauf** [comment]
@lbesnard I gonna bulid it.

**Comment by bpasquer** [comment]
@danfruehauf where is the manifest file coming from ? do i have to make changes to the pipeline to output such file or is it already implemented?

**Comment by danfruehauf** [comment]
@bpasquer Implemented for you, taken care of.

**Pull request merged**
