### PR TITLE
Add unique index on materialised view and refresh concurrently for AATAMS_SATTAG_DM

### PR DESCRIPTION
**Pull request by xhoenner**
@julian1 addresses https://github.com/aodn/internal-discussions/issues/228

### CODE REVIEW

**Comment by julian1** [comment]
@xhoenner Will this get deployed and tested on 14-nsp-mel, before it ends up in production?

**Comment by xhoenner** [comment]
Well I certainly hope so.

**Comment by julian1** [comment]
I'm not sure if that's an expression of confidence in our systems or not.

**Comment by xhoenner** [comment]
> I'm not sure if that's an expression of confidence in our systems or not.

Doesn't have anything to do with confidence, it's just me being overcautious. Would you mind deploying it on 14-nsp @julian1?

**Comment by julian1** [comment]
@lbesnard @mhidas @xhoenner I'm actually out of the loop so far as deploying harvesters. It would be better if one of you guys could do it - if it hasn't been done automatically.  

Cheers,

**Comment by xhoenner** [comment]
> I'm actually out of the loop so far as deploying harvesters.

I've never been in that loop unfortunately. @mhidas is away today, could you take care of that please @lbesnard ?

**Comment by lbesnard** [comment]
@julian1 
I could not build it on RC. See jenkins log 
```
[EnvInject] - Variables injected successfully.
[EnvInject] - Injecting contributions.
Building in workspace /home/jenkins/jobs/talend_rc/workspace
Copied 0 artifacts from "talend_build" build number 562
ERROR: Failed to copy artifacts from talend_build with filter: **/aatams_sattag_dm_harvester*
Archiving artifacts
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE
```

**Comment by xhoenner** [comment]
@jonescc any idea what went wrong here? This harvester requires mdb drivers (jar files) to read the MS Access files but I'm not sure that's what's causing the issue.

**Comment by jonescc** [comment]
Probably caused by recent work on jenkins to remove the jenkins slave.   Promoting from edge to rc requires the artifact built on edge - and it doesn't look like its present - rebuilding and promoting should fix the problem

**Comment by julian1** [comment]
Should probably go into planning since it brought down portal 123.

https://github.com/aodn/internal-discussions/issues/228

**Comment by lbesnard** [comment]
@jonescc rebuilding it didn't fix it

**Comment by jonescc** [comment]
OK - looks like the rebuild failed - raise as a VIT?

penJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000fa200000, 98566144, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 98566144 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/jenkins/jobs/talend_build/workspace/hs_err_pid2166.log
TOS_DI-linux-gtk-x86_64:
JVM terminated. Exit code=1
/usr/bin/java
-Xms64m
-Xmx1536m
-XX:MaxPermSize=512m
-Dfile.encoding=UTF-8
-jar /home/jenkins/talend/plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar
-os linux
-ws gtk
-arch x86_64
-launcher /home/jenkins/talend/TOS_DI-linux-gtk-x86_64
-name TOS_DI-linux-gtk-x86_64
--launcher.library /home/jenkins/talend/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1.R36x_v20100810/eclipse_1309.so
-startup /home/jenkins/talend/plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar
-exitdata 80000
--clean_component_cache
--disableShellInput
-consoleLog
-data /tmp/.talend-workspace
-componentDir /home/jenkins/talend/talend-components
-application au.org.emii.talend.codegen.Generator
-jobName aatams_sattag_dm_harvester
-projectDir /home/jenkins/jobs/talend_build/workspace/workspace/AATAMS_SATTAG_DM
-targetDir /home/jenkins/jobs/talend_build/workspace/target
-vm /usr/bin/java
-vmargs
-Xms64m
-Xmx1536m
-XX:MaxPermSize=512m
-Dfile.encoding=UTF-8
-jar /home/jenkins/talend/plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar 
	zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)

**Comment by xhoenner** [comment]
@pblain can you make this a VIT then please?

**Comment by pblain** [comment]
@xhoenner - sure

**Comment by julian1** [comment]
Is that a single malloc() call by the jvm for 100MB of contiguous memory?

Maybe add a swap file on jenkins?
```
root@15-aws-syd:~$ swapon -s
Filename                                Type            Size    Used    Priority
```

**Comment by julian1** [comment]
Possible options,

  - reduce number of jobs that can be run in parallel (currently 2 i think?)
  - investigate if there's anything else using system memory
  - increase VM instance memory from 8GB to 16GB
  - add a swap file.

I believe swap files are not normally recommended for VM's - since hitting swap will kill responsiveness of any service. On the other hand, it might be ok for jenkins since it's just a mechanism to handle a temporary spike for odd talend builds.

**Comment by julian1** [comment]
I wonder how much memory jenkins slave had? @jonescc

**Comment by jonescc** [comment]
So it looks like aatams_sattag_dm build fell over above due to memory not being available at that time.  Most likely due to the other jobs running on the system.

@xhoenner, I've reran the build this morning and have now deployed the new version to 14-nsp-mel.

Some action still needs to be taken as described by @julian1 to prevent build failures like the one above happening again.

**Comment by xhoenner** [comment]
Thanks for letting me know @jonescc. I pushed a few files to the incoming dir and the harvester has processed them successfully. Can you promote this harvester to prod then?

**Comment by jonescc** [comment]
OK its been promoted

**Comment by xhoenner** [comment]
Thanks @jonescc, I can't see the harvester yet on 10-aws but I suspect Chef needs to run first?

**Comment by julian1** [comment]
I kicked off another 10-aws provision. Here's the log in case you have permissions to read it, https://jenkins.aodn.org.au/job/chef_cook_node/7910/console

**Pull request merged**
