### PR TITLE
delete realtime harvesters

### PR DESCRIPTION
**Pull request by ana-berger**

### CODE REVIEW

**Review by bpasquer — COMMENTED** [review]
You went one step too far with the file deletion, we need to keep the current AODN_WAVE_NRT harvester

**Comment by ana-berger** [comment]
> You went one step too far with the file deletion, we need to keep the current AODN_WAVE_NRT harvester

oops, I thought we didn't have a harvester for RT, so just removed them all. I will fix it

**Comment by bpasquer** [comment]
> oops, I thought we didn't have a harvester for RT, so just removed them all. I will fix it

we don't have a pipeline since we are not ingesting files, but we do have a harvester that harvest data from the BOM WFS ;-)

**Comment by ana-berger** [comment]
yes, I mixed things up. Actually I think I did a rm `-r AODN_WAVE_NRT*` and then all was gone

**Pull request closed without merging**
