### PR TITLE
Harvester fixes

### PR DESCRIPTION
**Pull request by gsatimos**
tos7 harvester fixes

### CODE REVIEW

**Comment by jonescc** [comment]
Can't get AUS_CHLA_DB to build in the generator or in TOS.  Looks like talend is reloading GeoOperation from the installed routines.  I don't think changing the package for the jts wrapper makes sense here anyway - the resulting class doesn't exist.

**Comment by jonescc** [comment]
Other failing harvesters:

### ANMN_WAVE

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project harvest_awac: Compilation failure: Compilation failure:
[ERROR] /workspace/.build-workspace/ANMN_WAVE/poms/jobs/process/Subjobs/harvest_awac_0.1/src/main/java/anmn_wave/harvest_awac_0_1/harvest_awac.java:[6414]
[ERROR] org.postgis.Geometry o =
[ERROR] ^^^^^^^^^^^
[ERROR] org.postgis cannot be resolved to a type
[ERROR] /workspace/.build-workspace/ANMN_WAVE/poms/jobs/process/Subjobs/harvest_awac_0.1/src/main/java/anmn_wave/harvest_awac_0_1/harvest_awac.java:[6415]
[ERROR] org.postgis.PGgeometry.geomFromString(geom.toString());
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^
[ERROR] org.postgis.PGgeometry cannot be resolved to a type
[ERROR] 2 problems (2 errors)
[ERROR] -> [Help 1]

Looks like postgis jar is missing
```

### AODN_BOM_SEA_LEVEL

```
org.talend.designer.runprocess.ProcessorException: Missing jars: log4j-1.2.15.jar
```

### AODN_NT_SATTAG_OLIVERIDLEY

```
[ERROR]   
[ERROR]   The project org.example.aodn_nt_sattag_oliveridley.job:Harvest_data:0.1.0 (/workspace/.build-workspace/AODN_NT_SATTAG_OLIVERIDLEY/poms/jobs/process/aodn_nt_sattag_oliveridley_subjo
bs/harvest_data_0.1/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.artifactId' for org.talend.libraries:mvn:net.sourceforge.javacsv:javacsv with value 'mvn:net.sourceforge.javacsv' does not match a valid id pattern. @ li
ne 507, column 19
```

### HAWKSBILL_TURTLES_NT

```
[ERROR]   The project org.example.hawksbill_turtles_nt.job:Harvest_data:0.1.0 (/workspace/.build-workspace/HAWKSBILL_TURTLES_NT/poms/jobs/process/aodn_nt_sattag_hawksbill_subjobs/harvest_dat
a_0.1/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.artifactId' for org.talend.libraries:mvn:net.sourceforge.javacsv:javacsv with value 'mvn:net.sourceforge.javacsv' does not match a valid id pattern. @ li
ne 507, column 19
```

### AODN_NSW_OEH

```
org.talend.designer.runprocess.ProcessorException: Missing jars: log4j-1.2.15.jar
```

### AATAMS_SATTAG_NRT

```
[ERROR] /workspace/.build-workspace/AATAMS_SATTAG_NRT/poms/jobs/process/aatams_sattag_nrt_subjobs/filemetadata_harvest_0.1/src/main/java/aatams_sattag_nrt/filemetadata_harvest_0_1/FileMetada
ta_Harvest.java:[6171] 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project Data_Harvest: Compilation failure: Compilation failure:
[ERROR] /workspace/.build-workspace/AATAMS_SATTAG_NRT/poms/jobs/process/aatams_sattag_nrt_subjobs/data_harvest_1.1/src/main/java/aatams_sattag_nrt/data_harvest_1_1/Data_Harvest.java:[857]
[ERROR] Object source_Implicit_Context_Regex = /** Start field Implicit_Context_Regex:FILENAME */context.paramFile/** End field Implicit_Context_Regex:FILENAME */;
[ERROR] ^^^^^^^^^
[ERROR] paramFile cannot be resolved or is not a field
[ERROR] /workspace/.build-workspace/AATAMS_SATTAG_NRT/poms/jobs/process/aatams_sattag_nrt_subjobs/data_harvest_1.1/src/main/java/aatams_sattag_nrt/data_harvest_1_1/Data_Harvest.java:[861]
[ERROR] inImplicit_Context_Regex = new org.talend.fileprocess.TOSDelimitedReader(/** Start field Implicit_Context_Regex:FILENAME */context.paramFile/** End field Implicit_Context_Regex:FILEN
AME */, "ISO-8859-15", "", "\n", removeEmptyRowImplicit_Context_Regex);
[ERROR] ^^^^^^^^^
[ERROR] paramFile cannot be resolved or is not a field
[ERROR] /workspace/.build-workspace/AATAMS_SATTAG_NRT/poms/jobs/process/aatams_sattag_nrt_subjobs/data_harvest_1.1/src/main/java/aatams_sattag_nrt/data_harvest_1_1/Data_Harvest.java:[886]
[ERROR] inImplicit_Context_Regex = new org.talend.fileprocess.TOSDelimitedReader(/** Start field Implicit_Context_Regex:FILENAME */context.paramFile/** End field Implicit_Context_Regex:FILEN
AME */, "ISO-8859-15", "", "\n", removeEmptyRowImplicit_Context_Regex);
[ERROR] ^^^^^^^^^
[ERROR] paramFile cannot be resolved or is not a field
[ERROR] /workspace/.build-workspace/AATAMS_SATTAG_NRT/poms/jobs/process/aatams_sattag_nrt_subjobs/data_harvest_1.1/src/main/java/aatams_sattag_nrt/data_harvest_1_1/Data_Harvest.java:[7486]
[ERROR] fileName_talendStats_FILE = (new java.io.File(context.logDir+ "/" +"stats_file.txt")).getAbsolutePath().replace("\\","/");
[ERROR] ^^^^^^
[ERROR] logDir cannot be resolved or is not a field
[ERROR] /workspace/.build-workspace/AATAMS_SATTAG_NRT/poms/jobs/process/aatams_sattag_nrt_subjobs/data_harvest_1.1/src/main/java/aatams_sattag_nrt/data_harvest_1_1/Data_Harvest.java:[8396]
[ERROR] fileName_talendLogs_FILE = (new java.io.File(context.logDir+ "/" +"logs_file.txt")).getAbsolutePath().replace("\\","/");
[ERROR] ^^^^^^
[ERROR] logDir cannot be resolved or is not a field
[ERROR] 5 problems (5 errors)
```

### AODN_RAN_CTD

```
java.lang.RuntimeException: Job RAN_CTD_harvester not found
```

### AATAMS_SATTAG_DM

```
Caused by: org.talend.designer.runprocess.ProcessorException: java.lang.Exception: [ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.example.aatams_sattag_dm.job:Harvest_CTDdata:0.1.0 (/workspace/.build-workspace/AATAMS_SATTAG_DM/poms/jobs/process/aatams_sattag_dm_subjobs/harvest_ctddata_0.1/pom.
xml) has 1 error
[ERROR]     'dependencies.dependency.artifactId' for org.talend.libraries:mvn:net.sourceforge.javacsv:javacsv with value 'mvn:net.sourceforge.javacsv' does not match a valid id pattern. @ li
ne 507, column 19
```

### AODN_WAVE_NRT

```
org.talend.designer.runprocess.ProcessorException: Missing jars: log4j-1.2.15.jar
```

### SOOP_AUSCPR

```
org.talend.designer.runprocess.ProcessorException: Missing jars: log4j-1.2.15.jar
```

### AUS_PHYTO_DB

```
org.talend.commons.exception.PersistenceException: org.talend.designer.runprocess.ProcessorException: Routines "GeometryOperation" has compile errors
Error Line: 156
Detail Message: org.geotools.geometry.jts cannot be resolved
```

Looks like the same problem as AUS_CHLA_DB

### AODN_WAMSI_SEDIMENT

```
org.talend.designer.runprocess.ProcessorException: Missing jars: log4j-1.2.15.jar
```

**Comment by jonescc** [comment]
I'll add the log4j jar as discussed - should resolve a few of these.

**Comment by jonescc** [comment]
Looks like talend sdi is missing declared dependencies for gt-api-8.5.jar and gt-xsd-gml3-8.5.jar in plugin.xml in org.talend.sdi.designer.routines-7.0.1.  We should raise an issue/pull request against that repo (might wait until we finish testing as there may be other required changes).  Until then I'll create a patched zip for testing.

Looks like AUS_CHLA_DB is also missing the required netcdf module dependency for NetCDFUtils routines.  I'll create a new pull request removing the JTS path change made and including the required netcdf dependency to fix issues with this harvester.

**Comment by jonescc** [comment]
AUS_CHLA_DB fixed in https://github.com/aodn/harvesters/pull/689

**Comment by jonescc** [comment]
GeometryOperations/GeometryUtility dependency issues fixed by https://github.com/talend-spatial/talend-spatial/pull/76

Remaining issues with AUS_PHYTO_DB fixed in https://github.com/aodn/harvesters/pull/690

**Comment by jonescc** [comment]
ANMN_WAVE issue fixed by https://github.com/aodn/talend-components/commit/773c7bddb67d4eaa5b4f56347e8a58fa999c9d65 - needed postgis driver dependency to be added to iIncludeSdiComponents

**Comment by jonescc** [comment]
AODN_BOM_SEA_LEVEL fixed by including log4j-1.2.15.jar in maven repository

**Comment by jonescc** [comment]
AODN_NT_SATTAG_OLIVERIDLEY javacsv dependency issue fixed by https://github.com/aodn/talend-components/commit/7c7831bea6569f8c837b69a8790e1d15544b14a9

**Comment by jonescc** [comment]
HAWKSBILL_TURTLES_NT javacsv dependency issue also fixed by https://github.com/aodn/talend-components/commit/7c7831bea6569f8c837b69a8790e1d15544b14a9

**Comment by jonescc** [comment]
AODN_NSW_OEH build issues fixed by  including log4j-1.2.15.jar in maven repository and https://github.com/aodn/harvesters/pull/691

**Comment by jonescc** [comment]
Can we close this PR and delete the branch?

**Comment by gsatimos** [comment]
yeppers

**Pull request closed without merging**
