### PR TITLE
ABOS SOFS SURFACE FLUXES

### PR DESCRIPTION
**Pull request by lbesnard**
* renamed metadata context entries. *_dm_* to *_dm . similar for rt

### CODE REVIEW

**Comment by lbesnard** [comment]
@danfruehauf similar mod as to https://github.com/aodn/harvesters/pull/172

**Comment by danfruehauf** [comment]
I'll do the corresponding changes in the data bags then.

**Comment by mhidas** [comment]
@lbesnard Has this really been deployed to both RC and prod? They're both failing, but with different errors. For the issue on RC, I've suggested a solution in #199 

In prod, we're getting:

> Exception in component iIndexFiles_1_iIndexer
> java.sql.SQLException: No suitable driver found for jdbc:postgresql://null:null/null
>         at java.sql.DriverManager.getConnection(DriverManager.java:596)
>         at java.sql.DriverManager.getConnection(DriverManager.java:215)
>         at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.iIndexFiles_1_iFilesProcess(ABOS_SOFS_surfaceflux_harvester.java:2503)
>         at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.runJobInTOS(ABOS_SOFS_surfaceflux_harvester.java:4593)
>         at abos_sofs_surface_fluxes.abos_sofs_surfaceflux_harvester_1_0.ABOS_SOFS_surfaceflux_harvester.main(ABOS_SOFS_surfaceflux_harvester.java:4425)

Maybe some database config is missing?? Also, the java/build.properties file seems to imply this was build from commig 1b2f90, which was almost a year ago!

**Comment by lbesnard** [comment]
@mhidas Don't worry about the prod one. failing because the change I did on the chef was for both rc and prod. The think was that it wasn't suppose to take that much time.

**Pull request merged**
