### PR TITLE
FAIMMS - improve harvester for proper deletion of files

### PR DESCRIPTION
**Pull request by lbesnard**

### CODE REVIEW

**Comment by lbesnard** [comment]
@jonescc I made an attempt in improving the harvester to remove files.
I created a subjob called cleaned_data. However, this new deletion process doesn't get triggered at all on the po box doing po_s3_del although it appears as being deleted in the indexed_file table.

Would you mind having a look? cheers

**Comment by jonescc** [comment]
Doesn't look like the job name has been selected in the clean_data tRunJob in main_process_noqaqc and main_proces_qaqc:

image

**Comment by lbesnard** [comment]
@jonescc this seems to work fine on my po (ADD DELETE)

To Test with the utilities, best is to dl 
1) a FV00 file
2) a FV01 files of the same date

then del
both of them

for example
https://s3-ap-southeast-2.amazonaws.com/imos-data/IMOS/FAIMMS/Davies_Reef/Sensor_Float_1/sea_water_pressure@5.0m_channel_4701/2016/NO_QAQC/IMOS_FAIMMS_P_20160101T000000Z_DAVSF1_FV00.nc
https://s3-ap-southeast-2.amazonaws.com/imos-data/IMOS/FAIMMS/Davies_Reef/Sensor_Float_1/sea_water_pressure@5.0m_channel_4701/2016/QAQC/IMOS_FAIMMS_P_20160101T000000Z_DAVSF1_FV01.nc

If you're happy with this, I can do the same changed to the anmn nrs dar yon harvester

**Comment by jonescc** [comment]
Will test on 6-nec-hob

**Comment by jonescc** [comment]
Tested on 6-nec-hob with the following results:  
[faimms.zip](https://github.com/aodn/harvesters/files/3235060/faimms.zip)

@lbesnard tells me this is good.

**Pull request merged**
