### PR TITLE
 AODN_RAN_CTD:

### PR DESCRIPTION
**Pull request by bpasquer**
-add variable colour to deployment table  and map_view
-add tPostgresqlRow comonent to update the table and view accordingly
-activate subjob iUpdateSpatialExtent
-update context metedata with correct metadata UUID

### CODE REVIEW

**Comment by bpasquer** [comment]
@xhoenner Overall , same purpose as the AIMS CTD PR , but also took opportunity to edit additional context/subjob( see commit)
Thanks

**Comment by xhoenner** [comment]
This harvester ran fine on my machine, a few comments below before I merge this PR, mainly to prevent any slow Geoserver layers:

* Transmit whole context in Main job not ticked for UpdateMetadata subjob.
* No GIST index on the measurements and deployments tables.
* The measurements_t_idx on the measurements table should mirror the ORDER BY in the _data view.
* No index on the deployments table, which should mirror the ORDER BY in the _map view.

**Comment by bpasquer** [comment]
OK ,
I’ll fix that
On 17 Aug 2015, at 4:05 pm, Xavier Hoenner <notifications@github.com<mailto:notifications@github.com>> wrote:


This harvester ran fine on my machine, a few comments below before I merge this PR, mainly to prevent any slow Geoserver layers:

  *   Transmit whole context in Main job not ticked for UpdateMetadata subjob.
  *   No GIST index on the measurements and deployments tables.
  *   The measurements_t_idx on the measurements table should mirror the ORDER BY in the _data view.
  *   No index on the deployments table, which should mirror the ORDER BY in the _map view.

—
Reply to this email directly or view it on GitHub<https://github.com/aodn/harvesters/pull/268#issuecomment-131690401>.

Dr. Benedicte Pasquer - Project Officer
Monday - Friday 9am -3pm
IMOS e-Marine Information Infrastructure
University of Tasmania
Ph: +61 3 6226 1927













University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by xhoenner** [comment]
@ggalibert good to be deployed on rc.

**Comment by bpasquer** [comment]
@ggalibert  let me know when you deployed it so that i can check it ran fine. It will need to be deployed production straight after .

**Comment by ggalibert** [comment]
It's on RC and running now.

**Comment by ggalibert** [comment]
failed :
```
INFO 20/08/15 12:03 PM:liquibase: Reading from aodn_ran_ctd.databasechangelog
SEVERE 20/08/15 12:03 PM:liquibase: Change Set changelog.xml::index_measurments-5::talend failed.  Error: Error executing SQL CREATE INDEX me
asurements_file_id_idx ON measurements (file_id ASC NULLS LAST): ERROR: relation "measurements_file_id_idx" already exists
liquibase.exception.DatabaseException: Error executing SQL CREATE INDEX measurements_file_id_idx ON measurements (file_id ASC NULLS LAST): ER
ROR: relation "measurements_file_id_idx" already exists
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at aodn_ran_ctd.dataharvest_0_1.DataHarvest.iPostgresqlDbUpdate_1Process(DataHarvest.java:1228)
        at aodn_ran_ctd.dataharvest_0_1.DataHarvest.runJobInTOS(DataHarvest.java:3850)
        at aodn_ran_ctd.dataharvest_0_1.DataHarvest.runJob(DataHarvest.java:3682)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_3Process(RAN_CTD_harvester.java:1305)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_2Process(RAN_CTD_harvester.java:1189)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.runJobInTOS(RAN_CTD_harvester.java:3262)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.main(RAN_CTD_harvester.java:3070)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "measurements_file_id_idx" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:395)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 14 more
INFO 20/08/15 12:03 PM:liquibase: Successfully released change log lock
In finally block
Exception in component iPostgresqlDbUpdate_1
liquibase.exception.MigrationFailedException: Migration failed for change set changelog.xml::index_measurments-5::talend:
     Reason: liquibase.exception.DatabaseException: Error executing SQL CREATE INDEX measurements_file_id_idx ON measurements (file_id ASC NULLS LAST): ERROR: relation "measurements_file_id_idx" already exists:
          Caused By: Error executing SQL CREATE INDEX measurements_file_id_idx ON measurements (file_id ASC NULLS LAST): ERROR: relation "measurements_file_id_idx" already exists:
          Caused By: ERROR: relation "measurements_file_id_idx" already exists
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:347)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at aodn_ran_ctd.dataharvest_0_1.DataHarvest.iPostgresqlDbUpdate_1Process(DataHarvest.java:1228)
        at aodn_ran_ctd.dataharvest_0_1.DataHarvest.runJobInTOS(DataHarvest.java:3850)
        at aodn_ran_ctd.dataharvest_0_1.DataHarvest.runJob(DataHarvest.java:3682)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_3Process(RAN_CTD_harvester.java:1305)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_2Process(RAN_CTD_harvester.java:1189)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.runJobInTOS(RAN_CTD_harvester.java:3262)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.main(RAN_CTD_harvester.java:3070)
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE INDEX measurements_file_id_idx ON measurements (file_id ASC NULLS LAST): ERROR: relation "measurements_file_id_idx" already exists
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        ... 10 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "measurements_file_id_idx" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:395)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 14 more
Exception in component tRunJob_3
java.lang.RuntimeException: Child job running failed
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_3Process(RAN_CTD_harvester.java:1316)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.tRunJob_2Process(RAN_CTD_harvester.java:1189)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.runJobInTOS(RAN_CTD_harvester.java:3262)
        at aodn_ran_ctd.ran_ctd_harvester_0_1.RAN_CTD_harvester.main(RAN_CTD_harvester.java:3070)
finish;2015-08-20 12:03:51+10:00 0 minutes
```

**Pull request merged**
