### PR TITLE
Upgrade harvesters to use talend spatial 5.4.1

### PR DESCRIPTION
**Pull request by jonescc**
Any local Talend Open Studio installs will need to be upgraded to use this version of talend spatial - details to follow once compilation/testing is complete.

### CODE REVIEW

**Comment by danfruehauf** [comment]
How did you bulk update all of those harvesters?

**Comment by jonescc** [comment]
sed

**Comment by danfruehauf** [comment]
And what's the `SANDBOX` project?

**Comment by jonescc** [comment]
Thats a mistake - I'll remove it and the other mistake.  Wll-spotted

**Comment by jonescc** [comment]
OK, accidently committed local projects SANDBOX and UPDATEARGO removed

**Comment by danfruehauf** [comment]
Alright, lets rock.

**Pull request merged**
