### PR TITLE
New harvester for AATAMS_SATTAG_QC_CTD

### PR DESCRIPTION
**Pull request by xhoenner**
Pipeline needs to be implemented first before this harvester can be reviewed (classify into subfolder based on file name, e.g. ct101-790-13 goes into ct101 subfolder). Based on the Argo harvester as the netCDF files for this data collection roughly follow the Argo file format.

Will need new schema, login, data bags. Nat's already created a metadata record, UUID = 95d6314c-cfc7-40ae-b439-85f14541db71.

### CODE REVIEW

**Comment by xhoenner** [comment]
@lbesnard I've uploaded all files to 10aws:/home/xhoenner/AATAMS_SATTAG_QC_CTD. Thanks!

**Comment by lbesnard** [comment]
few comments so far. 

The files could pass the CF checker, they aren't very far from it
```
§3.1 Variables contain valid CF Units  :3:     0/ 4 : unknown units type (None)
                                                      for CYCLE_NUMBER, unknown
                                                      units type (psu) for PSAL,
                                                      unknown units type (psu)
                                                      for PSAL_ADJUSTED, unknown
                                                      units type (psu) for
                                                      PSAL_ADJUSTED_ERROR
§4 Axis attributes and coordinate varia:3:     2/ 3 : PRES is not allowed to
                                                      have an axis attr as it is
                                                      not a coordinate var or
                                                      auxiliary_coordinate_var
§4.4.1 Time and calendar               :1:     0/ 2 : Variable JULD should have
                                                      a calendar attribute,
                                                      Variable JULD_LOCATION
                                                      should have a calendar
                                                      attribute
```


Also the filename could be a bit closer to the IMOS filename convention such as 
http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=IMOS/AATAMS/AATAMS_sattag_nrt/Q9900181/profiles/

**Comment by lbesnard** [comment]
In order to be CF :
### to add/mod :
PSAL:units = "1e-3"
PSAL_ADJUSTED:units = "1e-3"
PSAL_ADJUSTED_ERROR:units = "1e-3"
CYCLE_NUMBER:units = "1"
JULD:calendar="julian";
JULD_LOCATION:calendar="julian";


### to remove
PRES:axis = "Z"

**Comment by xhoenner** [comment]
Excellent, thanks @lbesnard, I've contacted @fabien-roquet in this regard, he's the person in charge of producing the MEOP netCDF files.

**Comment by xhoenner** [comment]
Should be all good to go now @lbesnard

**Comment by lbesnard** [comment]
@xhoenner I made the files CF compliant with this

```
for nc_file in `find -type f`; do
   echo  $nc_file

   nc_has_variable $nc_file "PSAL" && ncatted -a units,PSAL,o,c,'1e-3' $nc_file

   nc_has_variable $nc_file "PSAL_ADJUSTED" && ncatted -a units,PSAL_ADJUSTED,o,c,'1e-3' $nc_file
   nc_has_variable $nc_file "PSAL_ADJUSTED_ERROR" && ncatted -a units,PSAL_ADJUSTED_ERROR,o,c,'1e-3' $nc_file
   nc_has_variable $nc_file "CYCLE_NUMBER" && ncatted -a units,CYCLE_NUMBER,o,c,'1' $nc_file
   nc_has_variable $nc_file "JULD" && ncatted -a calendar,JULD,o,c,'julian' $nc_file
   nc_has_variable $nc_file "JULD_LOCATION" && ncatted -a calendar,JULD_LOCATION,o,c,'julian' $nc_file

   nc_has_variable $nc_file "PRES" && ncatted -a axis,PRES,d,, $nc_file
done
```

**Pull request merged**
