### PR TITLE
AODN_NSW_OEH: harvest single-beam data

### PR DESCRIPTION
**Pull request by mhidas**
Ready to merge.

### CODE REVIEW

**Comment by mhidas** [comment]
If anyone could have a quick look and merge this, I'd love to test it in RC before I leave, i.e. today or tomorrow.

**Comment by mhidas** [comment]
Ooops, I forgot to update the UpdateMetadata subjob!

**Comment by xhoenner** [comment]
Looking all good to me @mhidas, although I haven't tested it on my PO box. Just re-activate the UpdateMetadata subjob and I'll merge you this PR.

**Comment by mhidas** [comment]
Thanks @xhoenner . Should be good to go now.
I won't be able to test it until I get back, but if @smancini is keen to move this along, he could get someone else to have a play with it. See also the linked PRs in data-services, and chef-private.
Test single-beam files are available in `10-aws-syd:/mnt/ebs/wip/NSW-OEH/STAX/`

**Comment by mhidas** [comment]
@xhoenner This is good to go now and I'm ready to test it.

**Pull request merged**
