### PR TITLE
New harvester PLANKTON_PRODUCTS

### PR DESCRIPTION
**Pull request by mhidas**
This will harvest all data products produced by the plankton group at CSIRO (for now only CPR phytoplankton products -- others to be added later)

### CODE REVIEW

**Comment by mhidas** [comment]
If anyone has time & appetite to do a quick review, I would be happy for some feedback. Independently of that, I would like to get this into RC next week.

@xhoenner @bpasquer @lbesnard

**Comment by bpasquer** [comment]
Thanks @xhoenner, I don't have much time to look at it this week.

**Comment by mhidas** [comment]
Thanks @xhoenner

**Comment by xhoenner** [comment]
Looking good @mhidas, my only question: why is the 'Delete metadata for deleted resources' subjob deactivated?

**Comment by mhidas** [comment]
Thanks @xhoenner. I don't think deletions will be needed for this harvester. Each product will be just one csv file, updated every now and then with a new one. Currently I don't see any need for the deletion function. There's more deveolopment to be done on this harvester later, so I'll rethink that at the time, but for now this should do.

**Pull request merged**
