### PR TITLE
Create anmn_all_map view for WMS/WFS

### PR DESCRIPTION
**Pull request by mhidas**
The idea is to create a WMS & WFS that allows filtering and access to **all** ANMN netcdf files.

### CODE REVIEW

**Comment by mhidas** [comment]
Would anybody care to take one minute to look at this and merge it? It's really just adding a view in the liquibase, and the added SQL can be seen here: https://github.com/aodn/harvesters/pull/377/files#diff-6b8d31234384ef8b852b0a9099298376

**Comment by danfruehauf** [comment]
@mhidas I can merge it and someone can post review it if you want.

**Comment by mhidas** [comment]
:+1: Thanks

**Comment by mhidas** [comment]
@danfruehauf Could you deploy it as well, please?

**Comment by danfruehauf** [comment]
> @danfruehauf Could you deploy it as well, please?

No worries.

**Pull request merged**
