### PR TITLE
Change all truncates in iPostgresqlOutput to clear

### PR DESCRIPTION
**Pull request by xhoenner**
Addresses https://github.com/aodn/harvesters/issues/311.

I still got an I/O error when testing this harvester on my VM @jonescc, let's see how rc behaves with the changes made to 
0d8ecb06-c5d0-11e6-8309-74a3258f47b6

### CODE REVIEW

**Comment by jonescc** [comment]
Looks like there is an issue building the talend components (kenkins.aodn.org.au not known).  I'll need to fix that before we can deploy to RC

**Comment by xhoenner** [comment]
sounds good, let me know when it's been deployed and I'll trigger it on rc

**Comment by jonescc** [comment]
@xhoenner - new version should have been deployed now

**Comment by xhoenner** [comment]
hmm still shows version 717 on 14-nec-hob.

**Comment by jonescc** [comment]
4-nec-hob is the new 14-nec-hob - try it there - believe its up and running now.

```
craigj@4-nec-hob:/mnt/ebs/talend/jobs/aatams_acoustic_reporting-aatams_acoustic_reporting$ talend_version aatams_acoustic_reporting-aatams_acoustic_reporting
GIT_COMMIT=5994fc24db6c339cbd84a964e67fb405a4fee8ec
BUILD_URL=https://jenkins.aodn.org.au/job/talend_build/738/
BUILD_TAG=jenkins-talend_build-738
ROOT_BUILD_CAUSE=MANUALTRIGGER
BUILD_JOB_NAME=talend_build
BUILD_CAUSE_MANUALTRIGGER=true
BUILD_DISPLAY_NAME=#738
BUILD_ID=738
BUILD_CAUSE=MANUALTRIGGER
BUILD_NUMBER=738
ROOT_BUILD_CAUSE_MANUALTRIGGER=true
```

**Pull request merged**
