### PR TITLE
Fix up the three satellite tagging data collections using the multi WFS capability

### PR DESCRIPTION
**Pull request by xhoenner**
Addresses https://github.com/aodn/content/issues/145. 

Data bags for AODN_NT_SATTAG_OLIVERIDLEY and AODN_NT_SATTAG_HAWKSBILL need to be updated (*i.e.* get rid of obsolete metadata context groups).

### CODE REVIEW

**Comment by lbesnard** [comment]
linked to aodn/chef-private#1685

**Comment by xhoenner** [comment]
deployed and ran successfully on rc, could you deploy these to prod?

**Comment by danfruehauf** [comment]
Easy. Deploying now...

**Comment by danfruehauf** [comment]
Deployed.

**Pull request merged**
