### PR TITLE
New harvester for AODN_RAN datasets

### PR DESCRIPTION
**Pull request by xhoenner**
Consolidates into a single harvester the old AODN_RAN_CTD harvester along with three additional RAN datasets.

As a consequence:
- The aodn_ran_ctd schema and user can be dropped.
- Need to create a new schema and user called aodn_ran.

Before this harvester can be deployed we need:
- Andrew Walsh to increase the RAN Geoserver download limit to 20,000.
- Three additional metadata records for the seabed, biolum and secchii datasets @smancini and @atkinsn.

### CODE REVIEW

**Comment by danfruehauf** [comment]
Does this also have a pipeline? You can't harvest from filesystem any more - you know...

**Comment by xhoenner** [comment]
Well the seabed, biolum and secchii datasets are harvested from the RAN Geoserver instance so that's alright. 

@bpasquer how does AODN_RAN_CTD work? I think it harvests data from the RAN Thredds catalogue but not sure whether those files are copied somewhere in our file system or whether we're just harvesting the content of their NetCDF files into our database.

**Comment by bpasquer** [comment]
@xhoenner  just harvesting the content

**Comment by xhoenner** [comment]
thanks @bpasquer. All good then @danfruehauf.

**Comment by atkinsn** [comment]
Hey @xhoenner I have created the metadata records in RC:
Seabed - 79c2df00-238c-4487-877a-15ffd624593d
Secchi - ded425e2-cbc9-418a-99ba-54a7bb17dcfa
Biolum - ce1d81d3-e7ee-47ac-af17-db1d01ca2494 
It will be a bit of time before they are ready to go, will need to do my editing, then gain extra info of Andrew Walsh, then get his approval for them.

**Comment by xhoenner** [comment]
Sounds good, thanks @atkinsn. Andrew hasn't increased the RAN Geoserver download limit to 20,000 so no rush to finalise those records.

**Pull request closed without merging**
