### PR TITLE
Event driven AATAMS_SATTAG_DM

### PR DESCRIPTION
**Pull request by danfruehauf**
Reverts aodn/harvesters#351

### CODE REVIEW

**Comment by danfruehauf** [comment]
OK, this PR works perfectly. At least so I believe.

@xhoenner We should experiment with that tomorrow + deploy.

**Comment by xhoenner** [comment]
Simplified harvester by removing 2nd index and harvest components. I tested it out @danfruehauf so it's ready to be deployed.

**Comment by danfruehauf** [comment]
> Simplified harvester by removing 2nd index and harvest components. I tested it out @danfruehauf so it's ready to be deployed.

Thanks. That's good. I guess we'll deploy it first thing tomorrow morning then.

Are you generally happy with the rest of the workflow?

**Comment by xhoenner** [comment]
Sounds good to me. Yes the new workflow looks good @danfruehauf, nice work putting all that together!

**Comment by danfruehauf** [comment]
> Sounds good to me. Yes the new workflow looks good @danfruehauf, nice work putting all that together!

I did the easy part. Talend is the hard part.

**Comment by danfruehauf** [comment]
@xhoenner And this also needs merging. I'll merge the chef part.

**Pull request merged**
